### ISSUE TITLE
关于简单的php函数漏洞和绕过 - HNightAnimal'Blog

### ISSUE THREAD

**Issue by HNightMan** [HNightMan/HNightMan.github.io#2]
https://hnightanimal.top/2019/05/02/%E5%85%B3%E4%BA%8E%E7%AE%80%E5%8D%95%E7%9A%84php%E5%87%BD%E6%95%B0%E6%BC%8F%E6%B4%9E%E5%92%8C%E7%BB%95%E8%BF%87/

**Comment by Es-id** [comment]
伟哥NB

**Comment by Es-id** [comment]
伟哥NB

**Comment by Es-id** [comment]
伟哥是我的偶像
